### ISSUE TITLE
Wrong port in Contoso sample 

### ISSUE THREAD

**Issue by ttustonic** [unoplatform/Uno.Samples#127]
Hello

UnoContoso.Service is configured to run on port 2706, but App.xaml.cs (in method UseRest) uses port 5000.
It should be changed to:

#if __ANDROID__
            var repository = new RestContosoRepository("http://10.0.2.2:2706/api/");
#else
            var repository = new RestContosoRepository("http://localhost:2706/api/");
#endif

**Comment by iury-kc** [comment]
Hi!
In my point of view, it depends on how you will debug the app. 
If you take a look at UnoContoso.Service /  launchSettings.json:

https://github.com/unoplatform/Uno.Samples/blob/b058cdc44c6f4793c200d3de331afc4e2513010e/UI/UnoContoso/UnoContoso.Service/Properties/launchSettings.json#L26

The port is 5000 since you are running on Kestrel. It will use 2706 if you debug throught IIS Express. 

On the other hand, we have a problem if we try to debug WASM and the Service at the same time using kestrel: both are using 5000.

I'm creating a PR proposing to chnage to 2706 as you asked for.  It will solve the conflict and avoid changes on code whatever webserver the developer choose.
