### ISSUE TITLE
How do I add a sample project?

### ISSUE THREAD

**Issue by kaki104** [unoplatform/Uno.Samples#31]
Hi

I converted Microsoft's Contoso UWP app to Uno Prism. I want to add this source to Samples, how do I do this?
Source : https://github.com/microsoft/Windows-appsample-customers-orders-database
Convert : https://github.com/kaki104/UnoContoso

**Comment by davidjohnoliver** [comment]
@kaki104  Great stuff!

You can add a folder containing your sample solution to the 'UI' folder: https://github.com/unoplatform/Uno.Samples/tree/master/UI. Include a readme in the sample folder if you've made one. 

You can also add your sample with a brief description to the list in the main readme: https://github.com/unoplatform/Uno.Samples/blob/master/README.md#samples

**Comment by kaki104** [comment]
@davidjohnoliver 
Seeing the method other people added, I thought I needed to create a Pull Request, so I proceeded in the following order.

- I cloned Uno.Samples locally.
- Created a branch named dev/UnoContoso.
- I created an UnoContoso folder in the UI folder.
- I copied my project to the folder.
- I commit and push, but an error occurred.

Opening repositories:
C:\Users\kaki1\Source\Repos\Uno.Samples
Pushing dev/UnoContoso
Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/unoplatform/Uno.Samples.git/': The requested URL returned error: 403
Pushing to https://github.com/unoplatform/Uno.Samples.git

Perhaps it's because I don't have permission. What should I do?

**Comment by davidjohnoliver** [comment]
@kaki104 Right, you'll need to create a Pull Request indeed. You can follow the guidance here: https://platform.uno/docs/articles/contributing/guidelines/pull-requests.html

The reason you're getting that error is because you need to [create a fork](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo) of Uno.Samples, and push your local branch to your remote fork then create the PR.

**Comment by kaki104** [comment]
I just created a pull request successfully. Thank you very much.
